name: Secrets

on:
  workflow_dispatch:

env:
  API_CSPROJ_PATH: "src/GithubActions.Api/GithubActions.Api.csproj"

jobs:
  secrets:
    name: Secrets
    runs-on: ubuntu-latest

    steps:
      - name: echo environment variable
        run: echo "$API_CSPROJ_PATH"